/**
 * Time marker extraction and equidistance validation utilities.
 *
 * The time segment markers (┃, U+2503) in progress bars are generated by
 * createTimeMarkers(divisions, barWidth) in packages/core/src/utils/bars.ts.
 *
 * Formal equidistance spec:
 *   segmentSize = Math.floor(barWidth / divisions)
 *   Markers placed at segmentSize * i for i = 1..divisions-1
 *   Due to integer division, last segment absorbs remainder.
 *   All internal gaps between adjacent markers must equal segmentSize.
 *   The last segment (from final marker to bar end) may be up to
 *   (divisions - 1) chars wider - this is by design.
 */

/** Extract column indices of all ┃ (U+2503) characters in a line string. */
export function extractMarkerPositions(line: string): number[] {
  const positions: number[] = [];
  for (let i = 0; i < line.length; i++) {
    if (line[i] === "\u2503") positions.push(i);
  }
  return positions;
}

/**
 * Validate that all gaps between adjacent markers are identical.
 * Returns true if equidistant, false otherwise.
 * 0 or 1 marker positions are trivially valid (no gaps to compare).
 */
export function validateEquidistant(positions: number[]): boolean {
  if (positions.length < 2) return true;
  const firstGap = positions[1] - positions[0];
  for (let i = 2; i < positions.length; i++) {
    if (positions[i] - positions[i - 1] !== firstGap) return false;
  }
  return true;
}

/**
 * Find all lines in a frame that contain ┃ markers, extract their positions,
 * and validate equidistance for each.
 */
export function extractAllMarkers(frame: string): Array<{
  lineIndex: number;
  line: string;
  positions: number[];
  gap: number | null;
  valid: boolean;
}> {
  const lines = frame.split("\n");
  const results: Array<{
    lineIndex: number;
    line: string;
    positions: number[];
    gap: number | null;
    valid: boolean;
  }> = [];

  for (let i = 0; i < lines.length; i++) {
    const positions = extractMarkerPositions(lines[i]);
    if (positions.length === 0) continue;
    const gap = positions.length >= 2 ? positions[1] - positions[0] : null;
    results.push({
      lineIndex: i,
      line: lines[i],
      positions,
      gap,
      valid: validateEquidistant(positions),
    });
  }
  return results;
}

/** Count bar-fill characters in a line.
 * Prediction bars use ▒ for the projected segment, which still contributes to total width.
 */
export function countBarChars(line: string): { filled: number; projected: number; empty: number; total: number } {
  let filled = 0;
  let projected = 0;
  let empty = 0;
  for (const c of line) {
    if (c === "\u2593") filled++;
    else if (c === "\u2592") projected++;
    else if (c === "\u2591") empty++;
  }
  return { filled, projected, empty, total: filled + projected + empty };
}

/** Find all lines containing bar chars and return their widths. */
export function extractBarWidths(frame: string): Array<{
  lineIndex: number;
  filled: number;
  projected: number;
  empty: number;
  total: number;
}> {
  const lines = frame.split("\n");
  return lines
    .map((line, i) => {
      const counts = countBarChars(line);
      if (counts.total === 0) return null;
      return { lineIndex: i, ...counts };
    })
    .filter(Boolean) as Array<{
    lineIndex: number;
    filled: number;
    projected: number;
    empty: number;
    total: number;
  }>;
}

/**
 * Count prediction bar characters (▓ U+2593, ▒ U+2592, ░ U+2591) in a line.
 * A "prediction bar" line contains ▒ (medium shade) which normal bars never use.
 */
export function countPredictionBarChars(line: string): {
  used: number; // ▓ count
  predicted: number; // ▒ count
  spare: number; // ░ count
  total: number;
  isPredictionBar: boolean;
} {
  let used = 0,
    predicted = 0,
    spare = 0;
  for (const c of line) {
    if (c === "\u2593") used++;
    else if (c === "\u2592") predicted++;
    else if (c === "\u2591") spare++;
  }
  const total = used + predicted + spare;
  return { used, predicted, spare, total, isPredictionBar: predicted > 0 };
}

/** Find all lines containing prediction bar chars (▒ medium shade). */
export function extractPredictionBars(frame: string): Array<{
  lineIndex: number;
  used: number;
  predicted: number;
  spare: number;
  total: number;
}> {
  const lines = frame.split("\n");
  return lines
    .map((line, i) => {
      const counts = countPredictionBarChars(line);
      if (!counts.isPredictionBar) return null;
      return { lineIndex: i, used: counts.used, predicted: counts.predicted, spare: counts.spare, total: counts.total };
    })
    .filter(Boolean) as Array<{
    lineIndex: number;
    used: number;
    predicted: number;
    spare: number;
    total: number;
  }>;
}
